
name: 'jaffle_shop'
version: '0.1'
profile: 'pg'
config-version: 2

vars:
  is_delta_load: True
  batch_name: "PC"
  delta_load_batch_id: -1
  delta_load_schema: cntrl
  completed_status: Completed # not used - result.status is "success" by default
  success_status: success
  started_status: started
  failed_status: Failed # not used - result.status is "error" by default
  error_status: error

on-run-start: "{{ mu_delta_load_master_control_start() }}"
on-run-end: "{{ mu_delta_load_master_control_complete() }}"

dispatch:
  - macro_namespace: dbt
    search_order: ['iag_delta_postgres_test', 'dbt']

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
snapshots:
  #on-run-start: "{{ insert_delta_load_master_control('PC') }}"
  iag_delta_postgres_test:
    orders:
      +tags: PC
    test:
      +tags: test
