version: 2

sources:
  - name: dev_nat
    tables:
      - name: raw_claims
      - name: cc_transaction_set_src_a
      - name: cc_transaction_set_src_b
      - name: cc_transaction_line_src_a
      - name: cc_transaction_line_src_b
      - name: cc_transaction_src_a
      - name: cc_transaction_src_b
models:
  - name: transaction
    description: This is an incremental transaction table

    columns:
      - name: claim_transaction_key
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
